app:
    build: .
    environment:
        REALM: prod
        REDIS_URL: "//redis:6379"
    links:
        - redis
    ports:
        - "81:8000"
    restart: unless-stopped

redis:
    image: redis
    restart: unless-stopped
